# Generated by Django 3.2.7 on 2021-09-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='econtact',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='eemail',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='eid',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='ename',
        ),
        migrations.AddField(
            model_name='employee',
            name='company_area',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='contractCountry',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_of_entry',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_registered',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='firstLastname',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='firstName',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='id_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='id_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='otherName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='secondLastname',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='state',
            field=models.CharField(default='Active', max_length=50, null=True),
        ),
    ]
